version: "3.8"

services:

  todo-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - todo-data:/var/lib/postgresql/data

volumes:
  todo-data:
